/* Generated by Yosys 0.20+1 (git sha1 60a787fa500, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module iiitb_SDM(sequence_in, clock, reset, detector_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  input clock;
  wire clock;
  wire [2:0] current_state;
  output detector_out;
  wire detector_out;
  wire [2:0] next_state;
  input reset;
  wire reset;
  input sequence_in;
  wire sequence_in;
  sky130_fd_sc_hd__a21boi_0 _14_ (
    .A1(current_state[1]),
    .A2(current_state[2]),
    .B1_N(sequence_in),
    .Y(next_state[0])
  );
  sky130_fd_sc_hd__clkinv_1 _15_ (
    .A(current_state[1]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__clkinv_1 _16_ (
    .A(current_state[2]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__and2b_2 _17_ (
    .A_N(current_state[0]),
    .B(sequence_in),
    .X(_06_)
  );
  sky130_fd_sc_hd__o21ai_0 _18_ (
    .A1(_04_),
    .A2(_06_),
    .B1(_05_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__and2b_2 _19_ (
    .A_N(sequence_in),
    .B(current_state[0]),
    .X(_08_)
  );
  sky130_fd_sc_hd__nor2_1 _20_ (
    .A(current_state[1]),
    .B(_08_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nor2_1 _21_ (
    .A(_09_),
    .B(_07_),
    .Y(next_state[1])
  );
  sky130_fd_sc_hd__or2b_2 _22_ (
    .A(current_state[0]),
    .B_N(sequence_in),
    .X(_10_)
  );
  sky130_fd_sc_hd__a21oi_1 _23_ (
    .A1(_10_),
    .A2(current_state[1]),
    .B1(current_state[2]),
    .Y(_11_)
  );
  sky130_fd_sc_hd__o22ai_1 _24_ (
    .A1(_04_),
    .A2(_05_),
    .B1(_06_),
    .B2(_08_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__nor2_1 _25_ (
    .A(_11_),
    .B(_12_),
    .Y(next_state[2])
  );
  sky130_fd_sc_hd__nand3_1 _26_ (
    .A(_04_),
    .B(current_state[0]),
    .C(sequence_in),
    .Y(_13_)
  );
  sky130_fd_sc_hd__nor3_1 _27_ (
    .A(_05_),
    .B(reset),
    .C(_13_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__clkinv_1 _28_ (
    .A(reset),
    .Y(_00_)
  );
  sky130_fd_sc_hd__clkinv_1 _29_ (
    .A(reset),
    .Y(_01_)
  );
  sky130_fd_sc_hd__clkinv_1 _30_ (
    .A(reset),
    .Y(_02_)
  );
  sky130_fd_sc_hd__dfxtp_1 _31_ (
    .CLK(clock),
    .D(_03_),
    .Q(detector_out)
  );
  sky130_fd_sc_hd__dfrtp_1 _32_ (
    .CLK(clock),
    .D(next_state[0]),
    .Q(current_state[0]),
    .RESET_B(_00_)
  );
  sky130_fd_sc_hd__dfrtp_1 _33_ (
    .CLK(clock),
    .D(next_state[1]),
    .Q(current_state[1]),
    .RESET_B(_01_)
  );
  sky130_fd_sc_hd__dfrtp_1 _34_ (
    .CLK(clock),
    .D(next_state[2]),
    .Q(current_state[2]),
    .RESET_B(_02_)
  );
endmodule
