/* Generated by Yosys 0.20+1 (git sha1 60a787fa500, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module iiitb_SDM(din, reset, clk, y);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  input clk;
  wire clk;
  wire [1:0] cst;
  input din;
  wire din;
  input reset;
  wire reset;
  output y;
  wire y;
  sky130_fd_sc_hd__clkinv_1 _06_ (
    .A(reset),
    .Y(_00_)
  );
  sky130_fd_sc_hd__nand2_1 _07_ (
    .A(cst[1]),
    .B(din),
    .Y(_05_)
  );
  sky130_fd_sc_hd__mux2i_1 _08_ (
    .A0(_05_),
    .A1(din),
    .S(cst[0]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nor4bb_1 _09_ (
    .A(din),
    .B(reset),
    .C_N(cst[1]),
    .D_N(cst[0]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__buf_1 _10_ (
    .A(din),
    .X(_02_)
  );
  sky130_fd_sc_hd__clkinv_1 _11_ (
    .A(reset),
    .Y(_01_)
  );
  sky130_fd_sc_hd__dfrtp_1 _12_ (
    .CLK(clk),
    .D(_02_),
    .Q(cst[0]),
    .RESET_B(_00_)
  );
  sky130_fd_sc_hd__dfrtp_1 _13_ (
    .CLK(clk),
    .D(_03_),
    .Q(cst[1]),
    .RESET_B(_01_)
  );
  sky130_fd_sc_hd__dfxtp_1 _14_ (
    .CLK(clk),
    .D(_04_),
    .Q(y)
  );
endmodule
